### ISSUE TITLE
Provide directory structure to the backend

### ISSUE THREAD

**Issue by MaxHass12** [neighborhood-app/backend#18]
- create the directory structure
- We might want to move `index.js` and `app.js` to `src/`

**Comment by MaxHass12** [comment]
Yo, lets do this first before moving on to write routes.

**Comment by radu-constantin** [comment]
Will do it tomorrow. We will have to keep adapting the structure according to our needs. As we've talked before, at this point I don't think we need a services layer, but maybe in the future we will realize that we need one.

**Comment by radu-constantin** [comment]
Actually, I'd like to take on this issue after we resolve the current pull requests.

**Comment by MaxHass12** [comment]
Makes sense.
