### ISSUE TITLE
Create routes for Neighborhood interactions.

### ISSUE THREAD

**Issue by radu-constantin** [neighborhood-app/backend#31]
1. Creating a neighborhood;
2. Deleting a neighborhood;
3. Editing aspects of a neighborhood;
4. Adding users/removing users;
6. Showing all neighborhoods;
7. Showing a particular neighborhood;
8. Creating a request in a neighborhood; (I think we can leave it as optional for now since I think we should also handle Users before working on this)

Write tests for each route.

**Comment by nina-dk** [comment]
I could work on creating & deleting so we can split this work up.

**Comment by radu-constantin** [comment]
Sounds good! Do you think we should make separate issues for each operation? Or just have this issue that encompasses all operations?

**Comment by nina-dk** [comment]
I think one is fine, it doesn't have that big a scope but perhaps each of us comments what they'll work on

**Comment by MaxHass12** [comment]
May be in the next meeting we can discuss the exact routes, and then divide them into 4 issues so each of us can work on our own separate branch on few routes. That way, the division of responsibility will be clearer.

**Comment by radu-constantin** [comment]
Separated into multiple issues.
