### ISSUE TITLE
Need further design work on neighborhood admin, three questions

### ISSUE THREAD

**Issue by RobertRodes** [neighborhood-app/backend#48]
1. When checking cascade deletes, I noticed that the `neighborhood.admin_id` is missing a foreign key constraint for the `users` table. This means that you can add admin id values that are not in the users table. We need to fix that. How would you like to proceed? I did this locally in psql: `ALTER TABLE neighborhoods ADD FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;`. I don't know whether you can use prisma to make table alterations like this or not. I can rerun the .sql files if needed, or perhaps Radu can put this command in an .sql file and run it on the github db.

2. So now we need to decide what to do when deleting a user who is an admin for a neighborhood. Do we automatically delete the neighborhood and its requests and responses as well, or do we do something else like assign a default admin? Beyond that, what do we do if a user decides to become inactive, and is an admin for a neighborhood? Maybe we have to further work out what an admin's responsibilities are before we decide what to do here.

3. Do we add the admin user to the `neighborhoods_users` table, meaning should the admin automatically be a user for a neighborhood? (I lean towards yes.)

**Comment by radu-constantin** [comment]
1. I can alter the Prisma schema directly. I'll make a separate issue for it.
2. We could prompt the user when he/she attempts to delete their account with something like this 'Deleting your account will also delete the neighborhoods that you administer. Please select a replacement before deleting your account.'
For the purposes of our MVP, it think this feature is not needed. We could work on it towards the end. What are your thoughts on this?
3. Yes!

**Comment by RobertRodes** [comment]
#2: If it isn't part of the MVP, that's fine, so long as we don't compromise integrity. We can cascade delete neighborhoods (and any associated requests and responses) when the associated admin is deleted. So, deal with it in the 2.0 version. :)
