### ISSUE TITLE
Implement "join" feature, where user joins a neighborhood

### ISSUE THREAD

**Issue by RobertRodes** [neighborhood-app/backend#62]
Add the appropriate information to the `_NeighborhoodToUser` table (neighborhood id and user id).

**Comment by MaxHass12** [comment]
This seems to be a repeat of issue 58.

**Comment by RobertRodes** [comment]
Yes it does. I'm not sure how to delete it.

**Comment by RobertRodes** [comment]
Duplicate of #58
